[package]
name = "brickhill_friend_bot"
version = "0.2.0"
authors = ["ayes-web"]
edition = "2018"

[dependencies]
thirtyfour = "0.15.1"
tokio = "0.2.22"
serde_json = "1.0.57"
reqwest = "0.10.8"
rand = "0.7.3"